name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 📂 Sync only changed files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6 
        with:
          server: ${{ secrets.FTP_SERVERNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21                 
          server-dir: htdocs/      
          local-dir: ./            
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: false           
          exclude: |               
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.env
            **/README.md
            **/package*.json
            **/composer.* 
            **/tests/**
          passive: true